[package]
name = "cockfight"
version = "0.0.0"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/initiavm.git", subdir = "precompile/modules/initia_stdlib", rev = "main" }

[addresses]
std =  "0x1"
addr = "0x3F4C26C0385D22009956EB3A4E8DBD095962485E"